/**
 * @file vm.c
 * @brief The Clox Virtual Machine (VM).
 *
 * This file implements the core of the Clox interpreter. The VM is a
 * stack-based machine that executes bytecode instructions generated by the
 * compiler. It manages the runtime stack, call frames for function calls,
 * global variables, and upvalues for closures.
 */

#include "vm.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#include "common.h"
#include "compiler.h"
#include "debug.h"
#include "memory.h"
#include "object.h"

// single global VM instance
VM vm;

// forward declarations
static void defineNative(const char* name, NativeFunction function);
static Value clockNative(const int32_t argCount __attribute__((unused)),
                         const Value* args __attribute__((unused)));
static void resetStack();

//-----------------------------------------------------------------------------
//- VM Initialization and Teardown
//-----------------------------------------------------------------------------

/**
 * @brief Initializes the virtual machine.
 *
 * Sets up the stack, global tables, and defines native functions.
 */
void initVM() {
    resetStack();
    vm.objects = NULL;
    vm.bytesAllocated = 0;
    vm.nextGC = 1024 * 1024;

    vm.grayCount = 0;
    vm.grayCapacity = 0;
    vm.grayStack = NULL;

    initTable(&vm.strings);
    initTable(&vm.globals);

    // pre-intern the "init" string for faster method lookups on class
    // initializers
    vm.initString = NULL;  // set to NULL for GC safety during copyString
    vm.initString = copyString("init", 4);

    // define native functions
    defineNative("clock", clockNative);
}

/**
 * @brief Frees all resources used by the VM.
 */
void freeVM() {
    freeTable(&vm.globals);
    freeTable(&vm.strings);
    vm.initString = NULL;
    freeObjects();
}

/**
 * @brief Resets the VM's stack to an empty state.
 */
static void resetStack() {
    vm.stackTop = vm.stack;
    vm.frameCount = 0;
    vm.openUpvalues = NULL;
}

//-----------------------------------------------------------------------------
//- Native Functions
//-----------------------------------------------------------------------------

/**
 * @brief Native function to return the elapsed CPU time.
 *
 * @param argCount The number of arguments (unused).
 * @param args A pointer to the arguments on the stack (unused).
 * @return Value The elapsed time as a number in miliseconds.
 */
static Value clockNative(const int32_t argCount __attribute__((unused)),
                         const Value* args __attribute__((unused))) {
    return NUMBER_VAL((double)clock());
}

/**
 * @brief Defines a native function and makes it available as a global variable.
 *
 * @param name The name of the native function in Clox.
 * @param function A C function pointer that implements the native behavior.
 */
static void defineNative(const char* name, NativeFunction function) {
    // pushing and poping to ensure garbage collector knows we're not done with
    // the function
    push(OBJECT_VAL(copyString(name, (int32_t)strlen(name))));
    push(OBJECT_VAL(newNative(function)));
    tableSet(&vm.globals, AS_STRING(vm.stack[0]), vm.stack[1]);
    pop();
    pop();
}

//-----------------------------------------------------------------------------
//- Stack Operations
//-----------------------------------------------------------------------------

/**
 * @brief Pushes a value onto the top of the stack.
 * @param value The value to push.
 */
void push(Value value) {
    *vm.stackTop = value;
    vm.stackTop++;
}

/**
 * @brief Pops and returns the value from the top of the stack.
 * @return Value The popped value.
 */
Value pop() {
    vm.stackTop--;
    return *vm.stackTop;
}

/**
 * @brief Returns a value from the stack without popping it.
 * @param distance The distance from the top of the stack (0 is the top).
 * @return Value The value at the specified distance.
 */
static Value peek(int32_t distance) { return vm.stackTop[-1 - distance]; }

//-----------------------------------------------------------------------------
//- Runtime Semantics
//-----------------------------------------------------------------------------

/**
 * @brief Reports a runtime error and prints a stack trace.
 * @param format A printf-style format string for the error message.
 * @param ... Arguments for the format string.
 */
static void runtimeError(
    const char* format,
    ...) {  // variadic function -> varying number of arguments
    va_list args;
    va_start(args, format);
    vfprintf(stderr, format, args);
    va_end(args);
    fputs("\n", stderr);

    // print a stack trace from the most recent call frame downwards
    for (int32_t i = vm.frameCount - 1; i >= 0; i--) {
        CallFrame* frame = &vm.frames[i];
        ObjectFunction* function = frame->closure->function;

        // -1 because the ip is sitting on the next instruction to be executed
        size_t instruction = frame->ip - function->chunk.code - 1;
        fprintf(stderr, "[line %d] in ", function->chunk.lines[instruction]);
        if (function->name == NULL) {
            fprintf(stderr, "script\n");
        } else {
            fprintf(stderr, "%s()\n", function->name->chars);
        }
    }

    resetStack();
}

/**
 * @brief Determines if a value is "falsey" in Clox.
 *
 * In Clox, only `nil` and `false` are falsey. Everything else is truthy.
 * @param value The value to check.
 * @return bool True if the value is falsey, false otherwise.
 */
static bool isFalsey(Value value) {
    return IS_NIL(value) || (IS_BOOL(value) && !AS_BOOL(value));
}

/**
 * @brief Concatenates two strings on top of the stack.
 */
static void concatenate() {
    const ObjectString* b = AS_STRING(peek(0));
    const ObjectString* a = AS_STRING(peek(1));

    int32_t length = a->length + b->length;
    char* chars = ALLOCATE(char, length + 1);
    memcpy(chars, a->chars, a->length);
    memcpy(chars + a->length, b->chars, b->length);
    chars[length] = '\0';

    ObjectString* result = takeString(chars, length);
    pop();
    pop();
    push(OBJECT_VAL(result));
}

//-----------------------------------------------------------------------------
//- Function and Method Calling
//-----------------------------------------------------------------------------

/**
 * @brief Prepares a new CallFrame to execute a function's code.
 * @param closure The closure being called.
 * @param argCount The number of arguments passed to the function.
 * @return bool True on success, false on error (e.g., stack overflow).
 */
static bool call(ObjectClosure* closure, int32_t argCount) {
    if (argCount != closure->function->arity) {
        runtimeError("Expected %d arguments, but got %d.",
                     closure->function->arity, argCount);
        return false;
    }

    if (vm.frameCount == FRAMES_MAX) {
        runtimeError("Stack overflow.");
        return false;
    }

    CallFrame* frame = &vm.frames[vm.frameCount++];
    frame->closure = closure;
    frame->ip = closure->function->chunk.code;
    // the function's stack window starts where the arguments were pushed
    frame->slots = vm.stackTop - argCount - 1;
    return true;
}

/**
 * @brief Calls a Clox value.
 *
 * Handles calls to functions, classes (constructors), bound methods, and
 * native functions.
 * @param callee The value to call.
 * @param argCount The number of arguments.
 * @return bool True on success, false on error.
 */
static bool callValue(Value callee, int32_t argCount) {
    if (IS_OBJECT(callee)) {
        switch (OBJECT_TYPE(callee)) {
            case OBJECT_BOUND_METHOD: {
                ObjectBoundMethod* bound = AS_BOUND_METHOD(callee);
                // the receiver (`this`) is placed in slot 0 for the method call
                vm.stackTop[-argCount - 1] = bound->receiver;
                return call(bound->method, argCount);
            }
            case OBJECT_CLASS: {
                ObjectClass* klass = AS_CLASS(callee);
                vm.stackTop[-argCount - 1] = OBJECT_VAL(newInstance(klass));
                Value initializer;
                if (tableGet(&klass->methods, vm.initString, &initializer)) {
                    return call(AS_CLOSURE(initializer), argCount);
                } else if (argCount != 0) {
                    runtimeError("expected 0 arguments, but got %d.", argCount);
                }
                return true;
            }
            case OBJECT_CLOSURE:
                return call(AS_CLOSURE(callee), argCount);
            case OBJECT_NATIVE: {
                NativeFunction native = AS_NATIVE(callee);
                Value result = native(argCount, vm.stackTop - argCount);
                vm.stackTop -= argCount + 1;
                push(result);
                return true;
            }
            default:
                break;  // non-callable object type
        }
    }
    runtimeError("Only functions and classes are callable.");
    return false;
}

/**
 * @brief Binds a method to an instance, creating a bound method object.
 * @param klass The class containing the method.
 * @param name The name of the method.
 * @return bool True on success, false if the method is not found.
 */
static bool bindMethod(ObjectClass* klass, ObjectString* name) {
    Value method;
    if (!tableGet(&klass->methods, name, &method)) {
        runtimeError("Undefined property '%s'.", name->chars);
        return false;
    }

    ObjectBoundMethod* bound = newBoundMethod(peek(0), AS_CLOSURE(method));
    pop();
    push(OBJECT_VAL(bound));
    return true;
}

/**
 * @brief Invokes a method from a specific class (used for `super` calls).
 * @param klass The class to find the method in.
 * @param name The method name.
 * @param argCount The number of arguments.
 * @return bool True on success, false on error.
 */
static bool invokeFromClass(ObjectClass* klass, ObjectString* name,
                            int32_t argCount) {
    Value method;
    if (!tableGet(&klass->methods, name, &method)) {
        runtimeError("Undefined property '%s'.", name->chars);
        return false;
    }
    return call(AS_CLOSURE(method), argCount);
}

/**
 * @brief Invokes a method on an instance.
 *
 * Looks for the method on the instance's class and calls it.
 * @param name The name of the method to invoke.
 * @param argCount The number of arguments.
 * @return bool True on success, false on error.
 */
static bool invoke(ObjectString* name, int32_t argCount) {
    Value receiver = peek(argCount);
    if (!IS_INSTANCE(receiver)) {
        runtimeError("Only instances have methods.");
        return false;
    }
    ObjectInstance* instance = AS_INSTANCE(receiver);

    Value value;
    if (tableGet(&instance->fields, name, &value)) {
        vm.stackTop[-argCount - 1] = value;
        return callValue(value, argCount);
    }

    return invokeFromClass(instance->klass, name, argCount);
}

//-----------------------------------------------------------------------------
//- Upvalue Management
//-----------------------------------------------------------------------------

/**
 * @brief Captures a local variable as an upvalue.
 *
 * If an upvalue for this local already exists, it is reused. Otherwise, a
 * new one is created and added to the VM's list of open upvalues.
 * @param local A pointer to the local variable on the stack.
 * @return ObjectUpvalue* The created or reused upvalue.
 */
static ObjectUpvalue* captureUpvalue(Value* local) {
    ObjectUpvalue* prevUpvalue = NULL;
    ObjectUpvalue* upvalue = vm.openUpvalues;

    // search through all upvalues whose local slot is above the one we're
    // looking for
    while (upvalue != NULL && upvalue->location > local) {
        prevUpvalue = upvalue;
        upvalue = upvalue->next;
    }

    // found an existing upvalue capturing the variable
    if (upvalue != NULL && upvalue->location == local) {
        return upvalue;
    }

    ObjectUpvalue* createdUpvalue = newUpvalue(local);
    createdUpvalue->next = upvalue;

    if (prevUpvalue == NULL) {
        vm.openUpvalues = createdUpvalue;
    } else {
        prevUpvalue->next = createdUpvalue;
    }

    return createdUpvalue;
}

/**
 * @brief Closes upvalues that are no longer in scope.
 *
 * When a local variable goes out of scope, any upvalue pointing to it must
 * be "closed" by copying the variable's value from the stack into the
 * upvalue object itself.
 * @param last A pointer to the stack slot at the boundary of the scope being
 * exited.
 */
static void closeUpvalues(const Value* last) {
    while (vm.openUpvalues != NULL && vm.openUpvalues->location >= last) {
        ObjectUpvalue* upvalue = vm.openUpvalues;
        upvalue->closed = *upvalue->location;
        upvalue->location = &upvalue->closed;
        vm.openUpvalues = upvalue->next;
    }
}

/**
 * @brief Defines a method on a class.
 *
 * The class and method are expected to be on top of the stack.
 * @param name The name of the method.
 */
static void defineMethod(ObjectString* name) {
    Value method = peek(0);
    ObjectClass* klass = AS_CLASS(peek(1));
    tableSet(&klass->methods, name, method);
    pop();  // pop the method closure
}

//-----------------------------------------------------------------------------
//- Main Execution Loop
//-----------------------------------------------------------------------------

/**
 * @brief The main execution loop of the VM.
 *
 * This function is the heart of the interpreter. It fetches, decodes, and
 * executes bytecode instructions one by one until the program terminates.
 * @return InterpretResult The result of the execution.
 */
static InterpretResult run() {
    CallFrame* frame = &vm.frames[vm.frameCount - 1];

    // Macros for reading from the bytecode stream.
#define READ_BYTE() (*frame->ip++)
#define READ_SHORT() \
    (frame->ip += 2, (uint16_t)((frame->ip[-2] << 8) | frame->ip[-1]))
#define READ_CONSTANT() \
    (frame->closure->function->chunk.constants.values[READ_BYTE()])
#define READ_STRING() AS_STRING(READ_CONSTANT())

    // Macro for binary numeric operations.
#define BINARY_OP(valueType, op)                          \
    do {                                                  \
        if (!IS_NUMBER(peek(0)) || !IS_NUMBER(peek(1))) { \
            runtimeError("Operands must be numbers.");    \
            return INTERPRET_RUNTIME_ERROR;               \
        }                                                 \
        double b = AS_NUMBER(pop());                      \
        double a = AS_NUMBER(pop());                      \
        push(valueType(a op b));                          \
    } while (false)

    for (;;) {
#ifdef DEBUG_TRACE_EXECUTION
        printf("            ");
        for (Value* slot = vm.stack; slot < vm.stackTop; slot++) {
            printf("[ ");
            printValue(*slot);
            printf(" ]");
        }
        printf("\n");
        disassembleInstruction(
            &frame->closure->function->chunk,
            (int32_t)(frame->ip - frame->closure->function->chunk.code));
#endif
        uint8_t instruction;
        switch (instruction = READ_BYTE()) {
            case OP_CONSTANT: {
                Value constant = READ_CONSTANT();
                push(constant);
                break;
            }
            case OP_NIL: {
                push(NIL_VAL);
                break;
            }
            case OP_TRUE: {
                push(BOOL_VAL(true));
                break;
            }
            case OP_FALSE: {
                push(BOOL_VAL(false));
                break;
            }
            case OP_POP: {
                pop();
                break;
            }
            case OP_GET_LOCAL: {
                uint8_t slot = READ_BYTE();
                push(frame->slots[slot]);
                break;
            }
            case OP_GET_UPVALUE: {
                uint8_t slot = READ_BYTE();
                push(*frame->closure->upvalues[slot]->location);
                break;
            }
            case OP_GET_PROPERTY: {
                if (!IS_INSTANCE(peek(0))) {
                    runtimeError("Only instances have properties.");
                    return INTERPRET_RUNTIME_ERROR;
                }

                ObjectInstance* instance = AS_INSTANCE(peek(0));
                ObjectString* name = READ_STRING();

                Value value;
                if (tableGet(&instance->fields, name, &value)) {
                    pop();  // instance
                    push(value);
                    break;
                }

                if (!bindMethod(instance->klass, name)) {
                    return INTERPRET_RUNTIME_ERROR;
                }
                break;
            }
            case OP_GET_GLOBAL: {
                ObjectString* name = READ_STRING();
                Value value;
                if (!tableGet(&vm.globals, name, &value)) {
                    runtimeError("Undefined variable '%s'.", name->chars);
                    return INTERPRET_RUNTIME_ERROR;
                }
                push(value);
                break;
            }
            case OP_GET_SUPER: {
                ObjectString* name = READ_STRING();
                ObjectClass* superclass = AS_CLASS(pop());
                if (!bindMethod(superclass, name)) {
                    return INTERPRET_RUNTIME_ERROR;
                }
                break;
            }
            case OP_DEFINE_GLOBAL: {
                // get the name of the variable from the constant table
                ObjectString* name = READ_STRING();
                // store it in the hash table with the name as the key
                tableSet(&vm.globals, name, peek(0));
                // remove the value from the stack
                pop();
                break;
            }
            case OP_SET_LOCAL: {
                uint8_t slot = READ_BYTE();
                frame->slots[slot] = peek(0);
                break;
            }
            case OP_SET_UPVALUE: {
                uint8_t slot = READ_BYTE();
                *frame->closure->upvalues[slot]->location = peek(0);
                break;
            }
            case OP_SET_PROPERTY: {
                if (!IS_INSTANCE(peek(1))) {
                    runtimeError("Only instances have fields.");
                    return INTERPRET_RUNTIME_ERROR;
                }

                ObjectInstance* instance = AS_INSTANCE(peek(1));
                tableSet(&instance->fields, READ_STRING(), peek(0));

                Value value = pop();  // remove value
                pop();                // remove instance
                push(value);          // add value back
                break;
            }
            case OP_SET_GLOBAL: {
                ObjectString* name = READ_STRING();
                if (tableSet(&vm.globals, name, peek(0))) {
                    tableDelete(&vm.globals, name);
                    runtimeError("Undefined variable '%s'.", name->chars);
                    return INTERPRET_RUNTIME_ERROR;
                }
                break;
            }
            case OP_EQUAL: {
                Value b = pop();
                Value a = pop();
                push(BOOL_VAL(valuesEqual(a, b)));
                break;
            }
            case OP_GREATER: {
                BINARY_OP(BOOL_VAL, >);
                break;
            }
            case OP_LESS: {
                BINARY_OP(BOOL_VAL, <);
                break;
            }
            case OP_ADD: {
                if (IS_STRING(peek(0)) && IS_STRING(peek(1))) {
                    concatenate();
                } else if (IS_NUMBER(peek(0)) && IS_NUMBER(peek(1))) {
                    // double b = AS_NUMBER(pop());
                    // double a = AS_NUMBER(pop());
                    // push(NUMBER_VAL(a + b));
                    BINARY_OP(NUMBER_VAL, +);
                } else {
                    runtimeError(
                        "Operands must be two numbers or two strings.");
                    return INTERPRET_RUNTIME_ERROR;
                }
                break;
            }
            case OP_SUBTRACT: {
                BINARY_OP(NUMBER_VAL, -);
                break;
            }
            case OP_MULTIPLY: {
                BINARY_OP(NUMBER_VAL, *);
                break;
            }
            case OP_DIVIDE: {
                BINARY_OP(NUMBER_VAL, /);
                break;
            }
            case OP_NOT: {
                push(BOOL_VAL(isFalsey(pop())));
                break;
            }
            case OP_NEGATE: {
                if (!IS_NUMBER(peek(0))) {
                    runtimeError("Operand must be a number.");
                    return INTERPRET_RUNTIME_ERROR;
                }
                push(NUMBER_VAL(-AS_NUMBER(pop())));
                break;
            }
            case OP_PRINT: {
                printValue(pop());
                printf("\n");
                break;
            }
            case OP_JUMP: {
                uint16_t offset = READ_SHORT();
                frame->ip += offset;
                break;
            }
            case OP_JUMP_IF_FALSE: {
                uint16_t offset = READ_SHORT();
                if (isFalsey(peek(0))) frame->ip += offset;
                break;
            }
            case OP_LOOP: {
                uint16_t offset = READ_SHORT();
                frame->ip -= offset;
                break;
            }
            case OP_CALL: {
                int32_t argCount = READ_BYTE();

                // function identifier is 'argCount' slots away
                if (!callValue(peek(argCount), argCount)) {
                    return INTERPRET_RUNTIME_ERROR;
                }
                frame = &vm.frames[vm.frameCount - 1];
                break;
            }
            case OP_INVOKE: {
                ObjectString* method = READ_STRING();
                int32_t argCount = READ_BYTE();
                if (!invoke(method, argCount)) {
                    return INTERPRET_RUNTIME_ERROR;
                }
                frame = &vm.frames[vm.frameCount - 1];
                break;
            }
            case OP_SUPER_INVOKE: {
                ObjectString* method = READ_STRING();
                int32_t argCount = READ_BYTE();
                ObjectClass* superclass = AS_CLASS(pop());
                if (!invokeFromClass(superclass, method, argCount)) {
                    return INTERPRET_RUNTIME_ERROR;
                }
                frame = &vm.frames[vm.frameCount - 1];
                break;
            }
            case OP_CLOSURE: {
                ObjectFunction* function = AS_FUNCTION(READ_CONSTANT());
                ObjectClosure* closure = newClosure(function);
                push(OBJECT_VAL(closure));
                for (int32_t i = 0; i < closure->upvalueCount; i++) {
                    uint8_t isLocal = READ_BYTE();
                    uint8_t index = READ_BYTE();
                    if (isLocal) {
                        closure->upvalues[i] =
                            captureUpvalue(frame->slots + index);
                    } else {
                        closure->upvalues[i] = frame->closure->upvalues[index];
                    }
                }
                break;
            }
            case OP_CLOSE_UPVALUE: {
                closeUpvalues(vm.stackTop - 1);
                pop();
                break;
            }
            case OP_RETURN: {
                Value result = pop();

                closeUpvalues(frame->slots);

                vm.frameCount--;
                if (vm.frameCount == 0) {  // check if the whole script is done
                    pop();                 // pop the implicit script function
                    return INTERPRET_OK;
                }

                vm.stackTop = frame->slots;
                push(result);

                frame = &vm.frames[vm.frameCount - 1];
                break;
            }
            case OP_CLASS: {
                push(OBJECT_VAL(newClass(READ_STRING())));
                break;
            }
            case OP_INHERIT: {
                Value superclass = peek(1);
                if (!IS_CLASS(superclass)) {
                    runtimeError("Superclass must be a class.");
                    return INTERPRET_RUNTIME_ERROR;
                }

                ObjectClass* subclass = AS_CLASS(peek(0));
                tableAddAll(&AS_CLASS(superclass)->methods, &subclass->methods);
                pop();
                break;
            }
            case OP_METHOD: {
                defineMethod(READ_STRING());
                break;
            }
        }
    }
#undef READ_STRING
#undef BINARY_OP
#undef READ_CONSTANT
#undef READ_SHORT
#undef READ_BYTE
}

//-----------------------------------------------------------------------------
//- Public Interpreter Interface
//-----------------------------------------------------------------------------

/**
 * @brief Interprets a string of Clox source code.
 *
 * This function orchestrates the entire process: compiling the source code
 * into bytecode and then executing that bytecode in the VM.
 *
 * @param source The Clox source code to interpret.
 * @return InterpretResult The result of the interpretation.
 */
InterpretResult interpret(const char* source) {
    ObjectFunction* function = compile(source);
    if (function == NULL) return INTERPRET_COMPILE_ERROR;

    // the compiler returns a function, which needs to be wrapped in a closure
    // before it can be called
    push(OBJECT_VAL(function));
    ObjectClosure* closure = newClosure(function);
    pop();
    push(OBJECT_VAL(closure));
    callValue(OBJECT_VAL(closure), 0);

    return run();
}
